### ISSUE TITLE
log file have only read permition

### ISSUE THREAD

**Issue by Guy-Markman** [Guy-Markman/Alon-Review#4]
@alonbl
Whenever I run the program I get the next error

```
Traceback (most recent call last):
  File "./08-daemon.py", line 79, in <module>
    main()
  File "./08-daemon.py", line 75, in main
    proc_child()
  File "./08-daemon.py", line 59, in proc_child
    util.write_to_target(log_fd, str(counter))
  File "/cygdrive/c/Users/Offer/Documents/GitHub/Alon-Review/EX04/util.py", line 9, in write_to_target
    text = text[os.write(target, text):]
OSError: [Errno 9] Bad file descriptor
```

When I checked the permitions for the log file I got found out the permitions are

`-rw-r--r-- `

Even though I gave the owner read write permition I get  the error.
Why is it happening?

**Comment by alonbl** [comment]
what program? why do you use this issues? it only makes it more difficult.
anyway, bad file descriptor means that you probably try to use invalid file descriptor, it has nothing to do with the actual file.

**Comment by Guy-Markman** [comment]
EX04/08-daemon.py
Anyway I fixed it.
Added O_WRONLY to the mode

**Comment by alonbl** [comment]
ok
